"""Synthetic member records. NOT REAL PEOPLE."""

MEMBERS = [
    {
        "member_id": "88214",
        "first_name": "Priya",
        "last_name": "Raghunathan",
        "dob": "1979-03-14",
        "sex": "F",
        "mrn": "MRN-0044128",
        "phone": "+1 559 555 0142",
        "email": "priya.r@example.invalid",
        "address": "418 Willow Creek Rd, Fresno, CA 93711",
        "diagnosis": "Right knee osteoarthritis, moderate",
        "allergies": ["Penicillin"],
        "programme": "Knee rehabilitation",
        "phase": 2,
        "session": 11,
        "sessions_total": 18,
        "last_pain_score": 5,
        "last_pain_logged": "2026-08-22",
        "medications": ["Meloxicam 15mg daily"],
        "prescriber": "Dr Anand Krishnamurthy",
        "insurance_member_number": "BX-4471902",
        "coach": "Akanksha Dessai",
        "status": "attention",
        "last_contact": "2026-08-19",
        "notes": "Reported increased swelling after session 9 and asked whether to continue.",
    },
    {
        "member_id": "88215",
        "first_name": "Daniel",
        "last_name": "Okonkwo",
        "dob": "1991-09-02",
        "sex": "M",
        "mrn": "MRN-0044129",
        "phone": "+1 559 555 0188",
        "email": "d.okonkwo@example.invalid",
        "address": "77 Adler Street, Clovis, CA 93611",
        "diagnosis": "Lumbar strain",
        "allergies": [],
        "programme": "Lower back",
        "phase": 1,
        "session": 4,
        "sessions_total": 6,
        "last_pain_score": 2,
        "last_pain_logged": "2026-08-24",
        "medications": [],
        "prescriber": None,
        "insurance_member_number": "BX-4471955",
        "coach": "Akanksha Dessai",
        "status": "ontrack",
        "last_contact": "2026-08-24",
        "notes": "Progressing well, no escalations.",
    },
    {
        "member_id": "88301",
        "first_name": "Marisol",
        "last_name": "Vega",
        "dob": "2013-04-12",
        "sex": "F",
        "mrn": "MRN-0044310",
        "phone": "+1 559 555 0211",
        "email": "vega.family@example.invalid",
        "address": "1204 Sierra Vista Ave, Fresno, CA 93703",
        "diagnosis": "Post-operative ACL rehabilitation",
        "allergies": ["Latex", "Sulfa drugs"],
        "programme": "Knee + ankle",
        "phase": 1,
        "session": 2,
        "sessions_total": 24,
        "last_pain_score": 7,
        "last_pain_logged": "2026-08-25",
        "medications": ["Ibuprofen 200mg as needed"],
        "prescriber": "Dr Helen Whitcombe",
        "insurance_member_number": "BX-4472108",
        "coach": "Akanksha Dessai",
        "status": "overdue",
        "last_contact": "2026-08-11",
        "notes": "Parent requested call back. Outreach 2 of 3.",
    },
]

STAFF = {
    "tok-coach-akanksha": {"name": "Akanksha Dessai", "role": "health_coach"},
    "tok-coach-ravi": {"name": "Ravi Menon", "role": "health_coach"},
    "tok-billing-sam": {"name": "Sam Ortiz", "role": "billing"},
}
